### ISSUE TITLE
干员名联想似乎出了点问题

### ISSUE THREAD

**Issue by KaronGH** [lie5860/ak-guess#1]
复现：输入“极光”，候选干员是“极光”和“铃兰”
预期：只出现“极光”

猜测是autocomplete匹配时出现问题

Update v1.0: alias.json第275行的正则有问题，"光|萝卜"会匹配上所有以“光”结尾的字符串，(按照我的理解)应该仅匹配单字“光”

**Comment by lie5860** [comment]
是的 应该只有当用户单独输入光或者萝卜的时候才会提示铃兰。这个代码已经修复了。会在下个版本发布。
![image](https://user-images.githubusercontent.com/30894657/157562187-bbec1712-2a56-421d-b085-f3e7f78ddaba.png)

感谢大佬的反馈。
